site_name: Knowledge Base
# site_description: for SEO
site_url: https://soilwise-he.github.io/SoilWise-documentation/
repo_url: https://github.com/soilwise-he/SoilWise-documentation
edit_uri: edit/main/knowledge-base/docs/

plugins:
  - search
  - mermaid2
  - git-revision-date-localized
  - glightbox
  - ezglossary
  - multirepo:
      keep_docs_dir: true
      repos:
        - section: LLA
          import_url: 'https://github.com/soilwise-he/link-liveliness-assessment?branch=main'
        - section: Validation
          import_url: 'https://github.com/soilwise-he/metadata-validator?branch=main'
        - section: MD Augmentation
          import_url: 'https://github.com/soilwise-he/metadata-augmentation?branch=main'
  - print-site:
      add_to_navigation: true
      print_page_title: 'Printable version'

git markdown_extensions:
  - def_list
  - admonition
  - tables
  - attr_list
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material

  palette:
    - primary: brown
    - accent: brown

  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.path
  - navigation.indexes
  - content.action.edit
  - content.footnote.tooltips

  logo: _assets/images/SoilWise_logo.png
#  favicon: assets/images/favicon.png

extra_css: 
    - extra.css
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/soilwise-project-eu/
      name: SoilWise on LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=61551552876700
      name: SoilWise on Facebook
  generator: false

copyright: Copyright &copy; 2023 - 2027 <a href="https://cordis.europa.eu/project/id/101112838">SoilWise Soil Mission Horizon Europe project No. 101112838</a>

